build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "taskflow/2.2.0"
    CONAN_USERNAME: "anotherfoxguy"
    CONAN_LOGIN_USERNAME: "anotherfoxguy"
    CONAN_CHANNEL: "stable"
    CONAN_UPLOAD: "https://api.bintray.com/conan/anotherfoxguy/conan-packages"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CONAN_VISUAL_VERSIONS: 15
    CONAN_BUILD_TYPES: Release
    CONAN_ARCHS: x86_64


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
